name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 
    - docker
    - test

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # - name: Create text file
      #   run: echo "maar dunga" > mytextfile.txt

      - name: Pull and run Docker image
        run: |
          docker pull alpine:latest
          docker run -d alpine:latest sleep 60
